# Generated by Django 4.1.3 on 2022-11-10 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, 'An hour')], default=60)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('interval', models.IntegerField(choices=[(1, 'Every week'), (2, 'Every two weeks'), (3, 'Every three weeks'), (4, 'Every four weeks')], default=1)),
                ('notes', models.TextField(blank=True, max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.studentprofile')),
            ],
        ),
    ]
