# Generated by Django 4.1.3 on 2022-11-20 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_adminprofile_user_alter_lessonrequest_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('CHILD', 'Child')], default='STUDENT', max_length=50),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.studentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
