# Generated by Django 4.1.3 on 2022-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_user_is_child_alter_user_type_childprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='recipient',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
