# Generated by Django 4.1.3 on 2022-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_user_is_child_studentprofile_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('DIRECTOR', 'Director')], default='STUDENT', max_length=50),
        ),
    ]
