# Generated by Django 4.1.3 on 2022-11-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_lessonrequest_recipient_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lessons.studentprofile'),
        ),
    ]
