# Generated by Django 4.1.3 on 2022-11-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_studentprofile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lessons.studentprofile'),
        ),
    ]
