# Generated by Django 4.1.3 on 2022-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_schoolterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolterm',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
