# Generated by Django 4.1.3 on 2022-11-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_schoolterm_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='school_term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='lessons.schoolterm'),
            preserve_default=False,
        ),
    ]
