# Generated by Django 4.1.3 on 2022-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lessonbooking_end_date_lessonbooking_school_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='regular_day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
