# Generated by Django 4.1.3 on 2022-11-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_alter_lessonbooking_regular_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='lessons.studentprofile')),
            ],
        ),
    ]
