# Generated by Django 4.1.3 on 2022-11-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_user_type_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='lessons.teacherprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('DIRECTOR', 'Director')], default='STUDENT', max_length=50),
        ),
    ]
