# Generated by Django 4.1.3 on 2022-11-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
        migrations.AddField(
            model_name='transfer',
            name='lesson_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='lessons.lessonbooking'),
            preserve_default=False,
        ),
    ]
