# Generated by Django 4.1.3 on 2022-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_lessonbooking_teacher_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbooking',
            name='teacher_name',
        ),
    ]
