# Generated by Django 4.1.3 on 2022-11-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_remove_transfer_sender_transfer_lesson_booking'),
        ('lessons', '0016_remove_lessonbooking_teacher_name'),
    ]

    operations = [
    ]
