# Generated by Django 4.1.3 on 2022-12-01 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_merge_20221130_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='repeat_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
