# Generated by Django 4.1.3 on 2022-12-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_lessonrequest_repeat_quantity_alter_transfer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='repeat_quantity',
        ),
    ]
