# Generated by Django 4.1.3 on 2022-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_remove_lessonrequest_repeat_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_repeat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
