# Generated by Django 4.1.3 on 2022-12-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_lessonrequest_is_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_repeat',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='previous_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonbooking'),
        ),
    ]
