# Generated by Django 4.1.3 on 2022-12-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_remove_lessonrequest_is_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='admin_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_bookings', to='lessons.adminprofile'),
        ),
    ]
